<%@ Page Title="" Language="C#" MasterPageFile="~/PaginaEdicion.Master" AutoEventWireup="true" CodeBehind="Administrador.aspx.cs" Inherits="ShopMarket.Vistas.Administrador.Administrador" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="contenidoCentral" runat="server">
    <div id="contenedorCentral">
        <br />
        <center>
            <asp:DropDownList ID="ddlAdmin" class="ddlAdmin" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlAdmin_SelectedIndexChanged">
                <asp:ListItem>--seleccionar--</asp:ListItem>
                <asp:ListItem>Categorias</asp:ListItem>
                <asp:ListItem>Productos</asp:ListItem>
                <asp:ListItem>Facturas</asp:ListItem>
                <asp:ListItem>Usuarios</asp:ListItem>
            </asp:DropDownList>
            <div class="categorias" style="margin-top:100px">
                <asp:GridView ID="grvCategorias"  runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" AutoGenerateColumns="False" OnRowDeleting="grvCategorias_RowDeleting" OnRowEditing="grvCategorias_RowEditing" OnRowUpdating="grvCategorias_RowUpdating" OnRowCancelingEdit="grvCategorias_RowCancelingEdit" OnPageIndexChanging="grvCategorias_PageIndexChanging">
                <Columns>
                    <asp:TemplateField HeaderText="ID-CATEGORIA">
                        <EditItemTemplate>
                            <asp:Label ID="lblIdCatEIT" runat="server" Text='<%# Bind("idCategoria") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblIdCategoria" runat="server" Text='<%# Bind("idCategoria") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="DESCRIPCION-CATEGORIA">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtEITcatDes" runat="server" Text='<%# Eval("descripcionCategoria") %>' ValidationGroup="1"></asp:TextBox>
                            &nbsp;
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDescripcion" runat="server" Text='<%# Bind("descripcionCategoria") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
                <br />
                <br />
                <asp:TextBox ID="txtDescripcionCategoria" placeholder="Descripcion de la categoria" runat="server" Visible="False" ValidationGroup="1" Width="200px"></asp:TextBox>&nbsp<asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txtDescripcionCategoria" ErrorMessage="Ingrese descripcion" Font-Bold="True" ForeColor="Red" ValidationGroup="1">*</asp:RequiredFieldValidator>
                <asp:Button ID="btnAgregarCategoria" runat="server" Text="Agregar" Visible="False" ValidationGroup="1" OnClick="btnAgregarCategoria_Click"></asp:Button>
                <br />
                <br />
                <asp:ValidationSummary ID="vsummaryCategorias" runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="1" />
            </div>
            <div class ="productos" style="top:100px;width: 100%;">
                <asp:TextBox ID="txtNombreProducto" runat="server" placeholder="ingrese nombre" Visible="False" Width="150px"></asp:TextBox>
                &nbsp;<asp:Button ID="btnFiltrarNombreProducto" runat="server" OnClick="btnFiltrarNombreProducto_Click" Text="Filtrar" Visible="False" />
&nbsp;
                <asp:DropDownList ID="ddlCategoriasArticulos" runat="server" AutoPostBack="True" OnSelectedIndexChanged="ddlCategoriasArticulos_SelectedIndexChanged" Width="200px">
                </asp:DropDownList>
&nbsp;<asp:Button ID="btnQuitarFiltros" runat="server" OnClick="btnQuitarFiltros_Click" Text="Quitar Filtros" />
                <br />
                <br />
                <asp:GridView ID="grvProductos" runat="server" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" PageSize="15" AutoGenerateColumns="False" OnRowCancelingEdit="grvProductos_RowCancelingEdit" OnRowDeleting="grvProductos_RowDeleting" OnRowEditing="grvProductos_RowEditing" Width="1000px" OnRowUpdating="grvProductos_RowUpdating" OnPageIndexChanging="grvProductos_PageIndexChanging" AllowSorting="True">
                <Columns>
                    <asp:TemplateField HeaderText="Numero de Articulo">
                        <EditItemTemplate>
                            <asp:Label ID="lblIdArticuloETgrvProdcuts" runat="server" Text='<%# Bind("idArticulo") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblIdArticuloGrvProductos" runat="server" Text='<%# Bind("idArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Categoria">
                        <EditItemTemplate>
                            <asp:DropDownList ID="ddlETcategoriasGrvArticulos" runat="server" DataSourceID="sqlDDLidCat" DataTextField="descripcionCategoria" DataValueField="idCategoria" Width="150px">
                            </asp:DropDownList>
                            <br />
                            <asp:SqlDataSource ID="sqlDDLidCat" runat="server" ConnectionString="<%$ ConnectionStrings:TpIntegradorProgramacionConnectionString %>" SelectCommand="SELECT [idCategoria], [descripcionCategoria] FROM [Categorias]"></asp:SqlDataSource>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblidCategoriaGrvProductos" runat="server" Text='<%# Bind("descripcionCategoria") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre de articulo">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtDescripcionArticuloET" runat="server" Text='<%# Bind("DescripcionArticulo") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDescripcionArticuloGrvProductos" runat="server" Text='<%# Bind("DescripcionArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtPrecioGrvProductos" runat="server" Text='<%# Bind("precioUnitarioArticulo") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecioETgrvProductos" runat="server" Text='<%# Bind("precioUnitarioArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Unidades En Stock">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtStockAgregar" runat="server" Text='<%# Bind("stockDisponibleArticulo") %>' TextMode="Number"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblStockETgrvProductos" runat="server" Text='<%# Bind("stockDisponibleArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
                &nbsp<br />
                <asp:TextBox ID="txtDescripcionArticulo" placeholder="Descripcion articulo" runat="server" Visible="False" ValidationGroup="2" Width="200px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="rfvDescripcion" runat="server" ControlToValidate="txtDescripcionArticulo" ErrorMessage="ingrese descripcion" ForeColor="Red" ValidationGroup="2">*</asp:RequiredFieldValidator>
                &nbsp<asp:TextBox ID="txtPrecioUnitario" placeholder="Precio unitario" runat="server" Visible="False" ValidationGroup="2" Width="200px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="rfvPrecioUnitario" runat="server" ControlToValidate="txtPrecioUnitario" ErrorMessage="Ingrese precio unitario" ForeColor="Red" ValidationGroup="2">*</asp:RequiredFieldValidator>
                &nbsp<asp:RegularExpressionValidator ID="revPrecio" runat="server" ControlToValidate="txtPrecioUnitario" ErrorMessage="Debe ser un numero decimal" ForeColor="Red" ValidationExpression="^[0-9]+([,][0-9]+)?$" ValidationGroup="2">*</asp:RegularExpressionValidator>
                <asp:TextBox ID="txtStock" placeholder="Stock a sumar" runat="server" Visible="False" TextMode="Number" ValidationGroup="2" Width="200px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="rfvStock" runat="server" ControlToValidate="txtStock" ErrorMessage="ingrese stock a sumar" ForeColor="Red" ValidationGroup="2">*</asp:RequiredFieldValidator>
                &nbsp<asp:TextBox ID="txtUrlImagen" placeholder="Url imagen" runat="server" Visible="False" ValidationGroup="2" Width="200px"></asp:TextBox>
                <asp:RequiredFieldValidator ID="rfvTxtImagen" runat="server" ControlToValidate="txtUrlImagen" ErrorMessage="Nombre de imagen" ForeColor="Red" ValidationGroup="2">*</asp:RequiredFieldValidator>
&nbsp;<asp:DropDownList ID="ddlCategoriasArt" runat="server">
                </asp:DropDownList>
&nbsp;<asp:Button ID="btnAgregarArticulo" runat="server" Text="Agregar" Visible="False" ValidationGroup="2" OnClick="btnAgregarArticulo_Click"></asp:Button>
                <br />
                <br />
                <asp:ValidationSummary ID="ValidationSummary2" runat="server" Font-Bold="True" ForeColor="Red" ValidationGroup="2" />
                <br />
            </div>
            <div class="facturas">
                <asp:Label ID="lblDesde" runat="server" Text="DESDE:" Visible="False"></asp:Label>
                <br />
                <asp:Calendar ID="Calendar1" runat="server" BackColor="White" BorderColor="Black" DayNameFormat="Shortest" Font-Names="Times New Roman" Font-Size="10pt" ForeColor="Black" Height="220px" NextPrevFormat="FullMonth" TitleFormat="Month" Visible="False" Width="400px">
                    <DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" ForeColor="#333333" Height="10pt" />
                    <DayStyle BorderColor="#33CCFF" BorderStyle="Solid" Width="14%" />
                    <NextPrevStyle Font-Size="8pt" ForeColor="White" />
                    <OtherMonthDayStyle ForeColor="#999999" />
                    <SelectedDayStyle BackColor="#CC3333" ForeColor="White" />
                    <SelectorStyle BackColor="#CCCCCC" Font-Bold="True" Font-Names="Verdana" Font-Size="8pt" ForeColor="#333333" Width="1%" />
                    <TitleStyle BackColor="Black" Font-Bold="True" Font-Size="13pt" ForeColor="White" Height="14pt" />
                    <TodayDayStyle BackColor="#CCCC99" />
                </asp:Calendar>
                <br />
                <asp:Label ID="lblHasta" runat="server" Text="HASTA:" Visible="False"></asp:Label>
                <br />
                <asp:Calendar ID="Calendar2" runat="server" BackColor="White" BorderColor="Black" DayNameFormat="Shortest" Font-Names="Times New Roman" Font-Size="10pt" ForeColor="Black" Height="220px" NextPrevFormat="FullMonth" TitleFormat="Month" Visible="False" Width="400px">
                    <DayHeaderStyle BackColor="#CCCCCC" Font-Bold="True" Font-Size="7pt" ForeColor="#333333" Height="10pt" />
                    <DayStyle BorderColor="#33CCFF" BorderStyle="Solid" Width="14%" />
                    <NextPrevStyle Font-Size="8pt" ForeColor="White" />
                    <OtherMonthDayStyle ForeColor="#999999" />
                    <SelectedDayStyle BackColor="#CC3333" ForeColor="White" />
                    <SelectorStyle BackColor="#CCCCCC" Font-Bold="True" Font-Names="Verdana" Font-Size="8pt" ForeColor="#333333" Width="1%" />
                    <TitleStyle BackColor="Black" Font-Bold="True" Font-Size="13pt" ForeColor="White" Height="14pt" />
                    <TodayDayStyle BackColor="#CCCC99" />
                </asp:Calendar>
                <br />
&nbsp;&nbsp;<br />
                <asp:Button ID="btnFiltrar" runat="server" OnClick="btnFiltrar_Click" Text="Filtrar" Visible="False" />
&nbsp;<asp:Button ID="btnQuitarFiltro" runat="server" OnClick="btnQuitarFiltro_Click" Text="Quitar filtro" Visible="False" />
                &nbsp;<asp:Button ID="btnMostrarReporte" runat="server" OnClick="btnMostrarReporte_Click" Text="Mostrar Reporte" />
                <br />
                <br />
            <asp:GridView ID="grvFacturas" runat="server" AllowPaging="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" PageSize="9" AutoGenerateColumns="False" AutoGenerateSelectButton="True" OnSelectedIndexChanging="grvFacturas_SelectedIndexChanging" OnPageIndexChanging="grvFacturas_PageIndexChanging">
                <Columns>
                    <asp:TemplateField HeaderText="Numero de factura">
                        <ItemTemplate>
                            <asp:Label ID="lblIdFactura" runat="server" Text='<%# Bind("id_Factura") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Dni comprador">
                        <ItemTemplate>
                            <asp:Label ID="lblDniUsuarioFactura" runat="server" Text='<%# Bind("dni_Usuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre Cliente">
                        <ItemTemplate>
                            <asp:Label ID="lblNombreCliente" runat="server" Text='<%# Bind("NombreCliente") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Fecha">
                        <ItemTemplate>
                            <asp:Label ID="lblFechaVenta" runat="server" Text='<%# Bind("fecha_venta") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Monto final">
                        <ItemTemplate>
                            <asp:Label ID="lblMontoFinal" runat="server" Text='<%# Bind("monto_final") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
                <br />
                <asp:Label ID="lblRecaudado" runat="server" Font-Bold="True" Font-Italic="True" Visible="False"></asp:Label>
                <br />
                <asp:Label ID="lblProductoMasVendido" runat="server" Font-Bold="True" Font-Italic="True" Visible="False"></asp:Label>
                <br />
                <asp:Label ID="lblCategoriaMasVendida" runat="server" Font-Bold="True" Font-Italic="True" Visible="False"></asp:Label>
                <br />
                <asp:Label ID="lblMejorCliente" runat="server" Font-Bold="True" Font-Italic="True" Visible="False"></asp:Label>
                <br />
                <br />
            <asp:GridView ID="grvDetalleFactura" style="top:100px" runat="server" AllowPaging="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" PageSize="9" AutoGenerateColumns="False" Width="500px" OnPageIndexChanging="grvDetalleFactura_PageIndexChanging">
                <Columns>
                    <asp:TemplateField HeaderText="Num Orden">
                        <ItemTemplate>
                            <asp:Label ID="lblNumOrden" runat="server" Text='<%# Bind("numeroDeOrden") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="ID Articulo">
                        <ItemTemplate>
                            <asp:Label ID="lblIDarticulo" runat="server" Text='<%# Bind("id_articulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Descripcion">
                        <ItemTemplate>
                            <asp:Label ID="lblDescripcionArticuloFacturas" runat="server" Text='<%# Bind("descripcionProducto") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Cantidad">
                        <ItemTemplate>
                            <asp:Label ID="lblCantidadDetalleFactura" runat="server" Text='<%# Bind("cantidad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <ItemTemplate>
                            <asp:Label ID="lblPrecioUnitarioFactura" runat="server" Text='<%# Bind("precio_unitario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
                <br />
            </div>
            <div class="usuarios">
                <asp:TextBox ID="txtNomUsuario" runat="server" placeholder="Nombre Usuario"></asp:TextBox>&nbsp<asp:Button ID="btnNombreUsuarioFiltrar" runat="server" OnClick="btnNombreUsuarioFiltrar_Click" Text="Filtrar" />
&nbsp;<asp:Button ID="BtnQuitarFiltroUsuario" runat="server" OnClick="BtnQuitarFiltroUsuario_Click" Text="Quitar Filtros" />
                <br />
                <asp:GridView ID="grvAdmin" style="top:100px" runat="server" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" AllowPaging="True" AutoGenerateEditButton="True" PageSize="9" OnPageIndexChanging="grvAdmin_PageIndexChanging" AutoGenerateColumns="False" Width="1000px" OnRowEditing="grvAdmin_RowEditing" OnRowCancelingEdit="grvAdmin_RowCancelingEdit" OnRowUpdating="grvAdmin_RowUpdating">
                <Columns>
                    <asp:TemplateField HeaderText="Dni">
                        <EditItemTemplate>
                            <asp:Label ID="lblDniEditIT" runat="server" Text='<%# Bind("dniUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDniGrv" runat="server" Text='<%# Bind("dniUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Nombre">
                        <EditItemTemplate>
                            <asp:Label ID="lblNombreUsuarioEdit" runat="server" Text='<%# Bind("NombreUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNombreUsuarioGrv" runat="server" Text='<%# Bind("NombreUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Apellido">
                        <EditItemTemplate>
                            <asp:Label ID="lblApellidoUsuarioEditIT" runat="server" Text='<%# Bind("ApellidoUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblApellidoUsuario" runat="server" Text='<%# Bind("ApellidoUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Email">
                        <EditItemTemplate>
                            <asp:Label ID="lblEmailEditIT" runat="server" Text='<%# Bind("emailUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblEmailGrv" runat="server" Text='<%# Bind("emailUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Direccion">
                        <EditItemTemplate>
                            <asp:Label ID="lblDireccionEditIT" runat="server" Text='<%# Bind("direccionUsuario") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblDireccionGrv" runat="server" Text='<%# Bind("direccionUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Admin">
                        <EditItemTemplate>
                            <asp:CheckBox ID="CheckBoxEstadoAdminUsuario" runat="server" Checked='<%# Bind("adminEstadoUsuario") %>' />
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblAdminGrv" runat="server" Text='<%# Bind("adminEstadoUsuario") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
            </asp:GridView>
            </div>
            <asp:Label ID="lblAgregar" runat="server" Font-Bold="True" Font-Overline="False"></asp:Label>
        </center>
    </div>
    <div class="confirmacion">
        <center>
            <asp:Label ID="lblPreguntaConfirmacion" runat="server" Visible="False"></asp:Label>
            <br />
            <asp:Button ID="btnAceptar" runat="server" Text="Aceptar" Visible="False" OnClick="btnAceptar_Click"></asp:Button>&nbsp<asp:Button ID="btnCancelar" runat="server" Text="Cancelar" Visible="False" OnClick="btnCancelar_Click"></asp:Button>
        </center>
    </div>
</asp:Content>
