<%@ Page Title="" Language="C#" MasterPageFile="~/PaginaEdicion.Master" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="ShopMarket.Carrito" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>



<asp:Content ID="Content2" ContentPlaceHolderID="contenidoCentral" runat="server">
    <div class="contenedorCentral">
        <center>
            <br />
            <asp:Label ID="lblGrv" runat="server" Font-Bold="True" Font-Italic="True" ForeColor="Blue"></asp:Label>
            <asp:Label ID="lblAviso" runat="server" Font-Bold="True" Font-Italic="True" ForeColor="Red" Text="DEBE INICIAR SESION PARA ACCEDER A ESTA INFORMACION" Visible="False"></asp:Label>
            <asp:GridView ID="grvCarrito" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" OnPageIndexChanging="grvCarrito_PageIndexChanging" OnRowCancelingEdit="grvCarrito_RowCancelingEdit" OnRowDeleting="grvCarrito_RowDeleting" OnRowEditing="grvCarrito_RowEditing" PageSize="20" Width="700px" OnRowUpdating="grvCarrito_RowUpdating" OnDataBound="grvCarrito_DataBound">
                <Columns>
                    <asp:TemplateField HeaderText="Nombre Producto">
                        <EditItemTemplate>
                            <asp:Label ID="lblNombreProd" runat="server" Text='<%# Bind("descripcionArticulo") %>'></asp:Label>
                            <br />
                            <asp:Label ID="lblIdArtET" runat="server" Text='<%# Bind("id_articulo") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblNomProducto" runat="server" Text='<%# Bind("descripcionArticulo") %>'></asp:Label>
                            <br />
                            <asp:Label ID="lblIdArt" runat="server" Text='<%# Bind("id_articulo") %>' Visible="False"></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Precio">
                        <EditItemTemplate>
                            <asp:Label ID="lblPrecioET" runat="server" Text='<%# Bind("precioUnitarioArticulo") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecio" runat="server" Text='<%# Bind("precioUnitarioArticulo") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Cantidad">
                        <EditItemTemplate>
                            <asp:TextBox ID="txtCantidad" runat="server" TextMode="Number" min="1"></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblCantidad" runat="server" Text='<%# Bind("cantidad") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Total">
                        <EditItemTemplate>
                            <asp:Label ID="lblPrecioFila" runat="server" Text='<%# Bind("Total") %>'></asp:Label>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="lblPrecioFila" runat="server" Text='<%# Bind("Total") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                </Columns>
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                <RowStyle BackColor="White" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="Gray" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
        </center>
    </div>
    <div class="preguntaConfirmacion" style="width:100%">
        <center>
            <br />
            <asp:Label ID="lblPreguntaConfirmacion" runat="server" Visible="False" ForeColor="Red">¿ESTA SEGURO QUE DESEA ELIMINAR ESTE PRODUCTO DE SU CARRITO?</asp:Label>
            <br />
            <asp:Button ID="btnAceptar" runat="server" Text="Aceptar" Visible="False" OnClick="btnAceptar_Click"></asp:Button>&nbsp<asp:Button ID="btnCancelar" runat="server" Text="Cancelar" Visible="False" OnClick="btnCancelar_Click"></asp:Button>
        </center>
    </div>
    <div class="finalizarCompra">
        <center>
            <asp:Button ID="btnFinalizarCompra" runat="server" Text="Finalizar Compra" OnClick="btnFinalizarCompra_Click" />
            <br />
            <asp:Label ID="lblPreguntaFinalizar" runat="server" Text="¿CONFIRMAR COMPRA?" ForeColor="Red" Visible="False"></asp:Label>
            <br />
            <asp:Button ID="btnConfirmar" runat="server" Text="Confirmar" OnClick="btnConfirmar_Click" Visible="False"></asp:Button>&nbsp<asp:Button ID="btnCancelarCompra" runat="server" Text="Cancelar" OnClick="btnCancelarCompra_Click" Visible="False"></asp:Button>
        </center>
    </div>
    </asp:Content>
